trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: terraform_init
  displayName: Terraform Init
  jobs:
  - job: terraform_init
    continueOnError: false
    steps:
    - task: PublishBuildArtifacts@1
      displayName: Publish Artifacts
      inputs:
        PathtoPublish: '$(System.DefaultworkingDirectory)/webapplication'
        ArtifactName: 'webapplication'
        publishLocation: 'Container'
    - task: TerraformInstaller@0
      displayName: Terraform Install
      inputs:
        terraformVersion: 'latest'
    - task: TerraformCLI@0
      displayName: Terraform init
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/webapplication'
        backendType: 'azurerm'
        backendServiceArm: 'TerraformAzureConnection'
        ensureBackend: true
        backendAzureRmResourceGroupName: 'infrastructure-rg'
        backendAzureRmResourceGroupLocation: 'eastus'
        backendAzureRmStorageAccountName: 'infraterraformstorage'
        backendAzureRmStorageAccountSku: 'Standard_LRS'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev-tfstate'
        allowTelemetryCollection: false
    - task: TerraformCLI@0
      displayName: Terraform Validate
      inputs:
        command: 'validate'
        allowTelemetryCollection: false
        workingDirectory: '$(System.DefaultWorkingDirectory)/webapplication'
    
    